version: 2

jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: make install
      - run: make test-unit
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
